from orchestrator.settings import PROJECT_DIR, WORKSPACE_STORAGE_MODE, WORKSPACES_PATH

WORKSPACES_PATH = WORKSPACES_PATH
WORKSPACE_STORAGE_MODE = WORKSPACE_STORAGE_MODE
ENGINE_PATH = PROJECT_DIR + "engine/"
