version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install pipenv
      - pipenv lock --requirements > requirements.txt
      - pip install -r requirements.txt