from flowyt.settings import ASYNC_MAX_CONCURRENCE, PROJECT_DIR, WORKSPACE_STORAGE_MODE, WORKSPACES_PATH

WORKSPACES_PATH = WORKSPACES_PATH
WORKSPACE_STORAGE_MODE = WORKSPACE_STORAGE_MODE
ENGINE_PATH = PROJECT_DIR + "engine/"
ASYNC_MAX_CONCURRENCE = ASYNC_MAX_CONCURRENCE
